### ISSUE TITLE
Bingo Detection Bug

### ISSUE THREAD

**Issue by zkxs** [minkcv/bingo#1]
## Expected behavior

Checking every square should result in 12 bingos

## Actual behavior

![image](https://user-images.githubusercontent.com/1807509/179300307-ccc141a0-fca3-4307-a97a-00e552c230e8.png)

I have been *scammed* out of four bingos! This bug is severely impacting my business!

**Comment by minkcv** [comment]
Fixed an issue totaling row bingos
